### ISSUE TITLE
use more git submodules

### ISSUE THREAD

**Issue by AcidNinjaFWHR** [paly2/Mynetest-server#17]
games/minetest_game should be a submodule (except if you modified something in it)
and mods too. (the more submodules we have, the easier it is to update)

**Comment by paly2** [comment]
Yes you are totally right, most of the mods (and the minetest_game) should be a submodule, except:
* 3d_armor is modified, however, some changes *might* be moved to the misc mod. Or not.
* broomstick (it is developped on our server)
* death_messages (we use a very modified version)
* farming_plus (it is a bit modified, and anyway is it not maintained anymore)
* first_hour (developped on our server)
* h2omes (very modified version)
* hudbars (many fixes, settings...)
* landcraft (developped on our server)
* lavasuit (entire rewrite of the original lavasuit mod)
* misc (obviously, because this mod is used to override the other ones)
* mobs_redo (simply named "mobs" in the mods directory, because of many changes in spawn probability, lifetimers... However this mod is still developped)
* names_per_ip (just useless, it is very small)
* nyantools (no official nyantools mod existing)
* pvpbutton (many changes)
* throwing (many fixes and changes, but in fact it would need an entire rewrite)
* the torch mod has to be removed (it has been moved to misc and is not used anymore)
* u_skins (more skins added :D)
* We added a whitelist to xban2. We could use the whitelist branch of https://github.com/paly2/xban2
* xdecor (missing textures, and other changes)

So the following need a submodule:
- [ ] minetest_game
- [x] MoreMesecons
- [ ] WorldEdit
- [ ] areas
- [ ] chesttools
- [ ] email
- [ ] fishing
- [ ] irc_modpack
- [ ] jumping
- [ ] mapfix
- [ ] maptools
- [ ] markers
- [x] mesecons
- [x] metatools
- [ ] moreores
- [ ] report
- [ ] signs_lib
- [ ] sprint ??
- [ ] unified_inventory
- [ ] vector_extras
- [ ] xban2 from [this fork](https://github.com/paly2/xban2) (use the whitelist branch)

**Comment by AcidNinjaFWHR** [comment]
Hey. I think you can't point metatools directly to @LeMagnesium because your pull requests haven't been merged there (and you point to your commit id which is still in the pull request). So either ask for merge or point to your fork :)

**Comment by paly2** [comment]
You are right, the changes on my fork may be useful

**Comment by paly2** [comment]
Waouh
